### Fetch All Posts
GET http://localhost:3000/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTc0ODU2MDY1MiwiZXhwIjoxNzQ4OTkyNjUyfQ.qoZTEvM5v77Kj7y6gi35xuiHj5SqpJtYrp2z2KK0wHI

### Fetch user Posts
GET http://localhost:3000/post/user/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTc0ODU2MDY1MiwiZXhwIjoxNzQ4OTkyNjUyfQ.qoZTEvM5v77Kj7y6gi35xuiHj5SqpJtYrp2z2KK0wHI


### Create Post
POST http://localhost:3000/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksImlhdCI6MTc0Nzk0NDgzNiwiZXhwIjoxNzQ4Mzc2ODM2fQ.D1dW2fnEQ293RQxzerB0i4ZH9VddJU2W9PKIFIK6EcM

{
  "firstName": "John",
  "lastName": "Doe",
  "description": "Funciona el web socket?",
  "location": "New York",
  "pictureId": "12345f",
  "picturePath": "https://images.unsplash.com/photo-1504595403659-9088ce801e29?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "userPicturePath": "https://images.unsplash.com/photo-1615109398623-88346a601842?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}

### Delete Post
DELETE  http://localhost:3000/post/34
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTc0Nzg2NTUzMCwiZXhwIjoxNzQ4Mjk3NTMwfQ.BuAP8O-vx1yoO7FxL-QpUAkaz4nAEAdCeSKvjTfaog8